/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * USTAT Explorer Backend
 * OpenAPI spec version: 1.0.0
 */
export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface OverviewHighestScoring {
  match_id: number;
  match_name: string;
  h_goal: number;
  a_goal: number;
}

export interface OverviewSeasonSummary {
  total_matches: number;
  total_goals: number;
  total_xg: number;
  xg_per_match: number;
  goal_per_match: number;
  home_win: number;
  home_win_percentage: number;
  away_win: number;
  away_win_percentage: number;
  draws: number;
  draw_percentage: number;
  avg_home_xg: number;
  avg_away_xg: number;
}

export type GetOverviewSeasonSummaryOverviewSeasonSummaryGetParams = {
league?: string;
season?: string;
};

export type GetOverviewHighestScoringOverviewHighestScoringGetParams = {
league?: string;
season?: string;
};

export type getOverviewSeasonSummaryOverviewSeasonSummaryGetResponse200 = {
  data: OverviewSeasonSummary
  status: 200
}

export type getOverviewSeasonSummaryOverviewSeasonSummaryGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getOverviewSeasonSummaryOverviewSeasonSummaryGetResponseSuccess = (getOverviewSeasonSummaryOverviewSeasonSummaryGetResponse200) & {
  headers: Headers;
};
export type getOverviewSeasonSummaryOverviewSeasonSummaryGetResponseError = (getOverviewSeasonSummaryOverviewSeasonSummaryGetResponse422) & {
  headers: Headers;
};

export type getOverviewSeasonSummaryOverviewSeasonSummaryGetResponse = (getOverviewSeasonSummaryOverviewSeasonSummaryGetResponseSuccess | getOverviewSeasonSummaryOverviewSeasonSummaryGetResponseError)

export const getGetOverviewSeasonSummaryOverviewSeasonSummaryGetUrl = (params?: GetOverviewSeasonSummaryOverviewSeasonSummaryGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/overview/season_summary?${stringifiedParams}` : `/overview/season_summary`
}

/**
 * @summary Get Overview Season Summary
 */
export const getOverviewSeasonSummaryOverviewSeasonSummaryGet = async (params?: GetOverviewSeasonSummaryOverviewSeasonSummaryGetParams, options?: RequestInit): Promise<getOverviewSeasonSummaryOverviewSeasonSummaryGetResponse> => {

  const res = await fetch(getGetOverviewSeasonSummaryOverviewSeasonSummaryGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOverviewSeasonSummaryOverviewSeasonSummaryGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOverviewSeasonSummaryOverviewSeasonSummaryGetResponse
}



export type getOverviewHighestScoringOverviewHighestScoringGetResponse200 = {
  data: OverviewHighestScoring
  status: 200
}

export type getOverviewHighestScoringOverviewHighestScoringGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getOverviewHighestScoringOverviewHighestScoringGetResponseSuccess = (getOverviewHighestScoringOverviewHighestScoringGetResponse200) & {
  headers: Headers;
};
export type getOverviewHighestScoringOverviewHighestScoringGetResponseError = (getOverviewHighestScoringOverviewHighestScoringGetResponse422) & {
  headers: Headers;
};

export type getOverviewHighestScoringOverviewHighestScoringGetResponse = (getOverviewHighestScoringOverviewHighestScoringGetResponseSuccess | getOverviewHighestScoringOverviewHighestScoringGetResponseError)

export const getGetOverviewHighestScoringOverviewHighestScoringGetUrl = (params?: GetOverviewHighestScoringOverviewHighestScoringGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/overview/highest_scoring?${stringifiedParams}` : `/overview/highest_scoring`
}

/**
 * @summary Get Overview Highest Scoring
 */
export const getOverviewHighestScoringOverviewHighestScoringGet = async (params?: GetOverviewHighestScoringOverviewHighestScoringGetParams, options?: RequestInit): Promise<getOverviewHighestScoringOverviewHighestScoringGetResponse> => {

  const res = await fetch(getGetOverviewHighestScoringOverviewHighestScoringGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOverviewHighestScoringOverviewHighestScoringGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOverviewHighestScoringOverviewHighestScoringGetResponse
}
