/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * USTAT Explorer Backend
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationError } from './validationError';

export interface HTTPValidationError {
  detail?: ValidationError[];
}
