/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * USTAT Explorer Backend
 * OpenAPI spec version: 1.0.0
 */

export interface OverviewHighestScoring {
  match_id: number;
  match_name: string;
  h_goal: number;
  a_goal: number;
}
