/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * USTAT Explorer Backend
 * OpenAPI spec version: 1.0.0
 */

export interface OverviewSeasonSummary {
  total_matches: number;
  total_goals: number;
  total_xg: number;
  xg_per_match: number;
  goal_per_match: number;
  home_win: number;
  home_win_percentage: number;
  away_win: number;
  away_win_percentage: number;
  draws: number;
  draw_percentage: number;
  avg_home_xg: number;
  avg_away_xg: number;
}
