/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * USTAT Explorer Backend
 * OpenAPI spec version: 1.0.0
 */

export interface OverviewGoalAndXGPerMatch {
  selected_goal_per_match: number;
  highest_goal_per_match: number;
  lowest_goal_per_match: number;
  average_goal_per_match: number;
  selected_xg_per_match: number;
  highest_xg_per_match: number;
  lowest_xg_per_match: number;
  average_xg_per_match: number;
}
