/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * USTAT Explorer Backend
 * OpenAPI spec version: 1.0.0
 */

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}
